CREATE DATABASE DB_PIZZARIA 
GO
USE DB_PIZZARIA
GO
CREATE TABLE TB_CATEGORIA
(
	ID_CATEGORIA INT IDENTITY NOT NULL
	,NM_CATEGORIA VARCHAR(255) NOT NULL
	,DS_CATEGORIA VARCHAR(255)
	,CONSTRAINT PK_TB_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
)
GO

CREATE TABLE TB_PRODUTOS
(
    ID_PRODUTO INT IDENTITY NOT NULL
   ,NM_PRODUTO VARCHAR(255) NOT NULL
   ,VL_PRODUTO FLOAT NOT NULL
   ,DS_PRODUTO VARCHAR(255)
   ,ID_CATEGORIA INT NOT NULL 
   ,CONSTRAINT FK_CATPROD FOREIGN KEY(ID_CATEGORIA) REFERENCES TB_CATEGORIA (ID_CATEGORIA)
   ,CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY(ID_PRODUTO)       
)
GO



CREATE TABLE TB_CLIENTES
(
	ID_CLIENTE INT IDENTITY NOT NULL
	,NM_CLIENTE VARCHAR(100) NOT NULL
	,NR_TELEFONE VARCHAR(13) NOT NULL
	,DS_ENDERECO VARCHAR(100) NOT NULL
	,DS_BAIRRO VARCHAR(50) NOT NULL
	,CONSTRAINT PK_TB_CLIENTES PRIMARY KEY(ID_CLIENTE)
)
GO

CREATE TABLE TB_STATUS
(
	ID_STATUS INT IDENTITY NOT NULL
	,NM_STATUS VARCHAR(255) NOT NULL
	,CONSTRAINT PK_TB_STATUS PRIMARY KEY (ID_STATUS)
)
GO

CREATE TABLE TB_PEDIDOS
(
	ID_PEDIDO INT IDENTITY NOT NULL
	,ID_CLIENTE INT NOT NULL 
	,ID_STATUS INT NOT NULL
	,DS_FORMAPAG VARCHAR(30)
	,CONSTRAINT PK_TB_PEDIDOS PRIMARY KEY (ID_PEDIDO)
	,CONSTRAINT FK_PEDCLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTES (ID_CLIENTE)
	,CONSTRAINT FK_PEDSTATUS FOREIGN KEY (ID_STATUS) REFERENCES TB_STATUS (ID_STATUS)
)
GO

CREATE TABLE TB_ITEM_PEDIDOS 
(
	ID_ITEM_PEDIDO INT IDENTITY NOT NULL
	,ID_PEDIDO INT NOT NULL
	,ID_PRODUTO INT NOT NULL
	,QT_PRODUTO FLOAT NOT NULL
	,CONSTRAINT PK_TB_ITEM_PEDIDOS PRIMARY KEY (ID_ITEM_PEDIDO)
	,CONSTRAINT FK_ITEMPED FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDOS (ID_PEDIDO)
	,CONSTRAINT FK_PEDIDOPRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTOS (ID_PRODUTO)
)


INSERT TB_STATUS (NM_STATUS) VALUES ('Entregue')
INSERT TB_STATUS (NM_STATUS) VALUES ('Em andamento')
INSERT TB_STATUS (NM_STATUS) VALUES ('Cancelado')

SELECT TB_PRODUTOS.NM_PRODUTO, TB_CATEGORIA.NM_CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIA
ON TB_PRODUTOS.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA


SELECT TB_PEDIDOS.ID_PEDIDO, TB_CLIENTES.NM_CLIENTE, TB_STATUS.NM_STATUS, TB_PEDIDOS.DS_FORMAPAG 
FROM TB_PEDIDOS 
INNER JOIN TB_CLIENTES ON TB_PEDIDOS.ID_CLIENTE = TB_CLIENTES.ID_CLIENTE
INNER JOIN TB_STATUS ON TB_PEDIDOS.ID_STATUS = TB_STATUS.ID_STATUS 

SELECT TB_CLIENTES.ID_CLIENTE, TB_CLIENTES.NM_CLIENTE, TB_PEDIDOS.ID_PEDIDO, TB_PRODUTOS.NM_PRODUTO, TB_ITEM_PEDIDOS.QT_PRODUTO
FROM TB_ITEM_PEDIDOS
INNER JOIN TB_PEDIDOS ON TB_ITEM_PEDIDOS.ID_PEDIDO=TB_PEDIDOS.ID_PEDIDO
INNER JOIN TB_CLIENTES ON TB_PEDIDOS.ID_CLIENTE = TB_CLIENTES.ID_CLIENTE
INNER JOIN TB_PRODUTOS ON TB_ITEM_PEDIDOS.ID_PRODUTO = TB_PRODUTOS.ID_PRODUTO
