USE DB_AGENDA
INSERT INTO TB_PRODUTOS(NM_PRODUTO, VL_PRODUTO, DS_PRODUTO, ID_CATEGORIA) VALUES ('Pizza', '10.5', 'pizza pizza', '2')
INSERT INTO TB_PRODUTOS(NM_PRODUTO, VL_PRODUTO, DS_PRODUTO, ID_CATEGORIA) VALUES ('FANTA', '10.5', 'pizza pizza', '5')

SELECT TB_PRODUTOS.NM_PRODUTO, TB_CATEGORIA.NM_CATEGORIA
FROM TB_PRODUTOS
INNER JOIN TB_CATEGORIA
ON TB_PRODUTOS.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA

SELECT * FROM TB_CATEGORIA

SELECT * FROM TB_CLIENTES
SELECT * FROM TB_PEDIDOS
SELECT * FROM TB_STATUS
SELECT * FROM TB_ITEM_PEDIDOS
SELECT * FROM TB_PRODUTOS

INSERT TB_STATUS (NM_STATUS) VALUES ('Entregue')
INSERT TB_STATUS (NM_STATUS) VALUES ('Em andamento')
INSERT TB_STATUS (NM_STATUS) VALUES ('Cancelado')

SELECT * FROM TB_PEDIDOS
INSERT TB_PEDIDOS(ID_CLIENTE, ID_STATUS, DS_FORMAPAG) VALUES ('7','1','Dinheiro')

SELECT TB_PEDIDOS.ID_PEDIDO, TB_CLIENTES.NM_CLIENTE, TB_STATUS.NM_STATUS, TB_PEDIDOS.DS_FORMAPAG 
FROM TB_PEDIDOS 
INNER JOIN TB_CLIENTES ON TB_PEDIDOS.ID_CLIENTE = TB_CLIENTES.ID_CLIENTE
INNER JOIN TB_STATUS ON TB_PEDIDOS.ID_STATUS = TB_STATUS.ID_STATUS 


SELECT NM_STATUS FROM TB_STATUS WHERE ID_STATUS=1


INSERT TB_ITEM_PEDIDOS (ID_PEDIDO, ID_PRODUTO, QT_PRODUTO) VALUES ('54', '7', '1')

SELECT TB_CLIENTES.ID_CLIENTE, TB_CLIENTES.NM_CLIENTE, TB_PEDIDOS.ID_PEDIDO, TB_PRODUTOS.NM_PRODUTO, TB_ITEM_PEDIDOS.QT_PRODUTO
FROM TB_ITEM_PEDIDOS
INNER JOIN TB_PEDIDOS ON TB_ITEM_PEDIDOS.ID_PEDIDO=TB_PEDIDOS.ID_PEDIDO
INNER JOIN TB_CLIENTES ON TB_PEDIDOS.ID_CLIENTE = TB_CLIENTES.ID_CLIENTE
INNER JOIN TB_PRODUTOS ON TB_ITEM_PEDIDOS.ID_PRODUTO = TB_PRODUTOS.ID_PRODUTO

